### ISSUE TITLE
Odd return values when user accidently supplies a three letter country code

### ISSUE THREAD

**Issue by godfoder** [VertNet/api-geospatial#1]
The system obviously is able to match the country code, and compute a valid distance, but it returns a value indicating that it isn't inside the country. Desired return values would either be to properly handle either 2 or 3 digit codes, or otherwise completely reject 3 digit codes (validCountry:False) to avoid confusion.

{
  "decimalLongitude": "-82.336173",
  "flags": {
    "negatedLatitude": "False",
    "hasScientificName": "True",
    "validCountry": "True",
    "negatedLongitude": "False",
    "validCoordinates": "True",
    "distanceToCountryInKm": 0,
    "hasCountry": "True",
    "coordinatesInsideCountry": "False",
    "transposedCoordinates": "False",
    "hasCoordinates": "True",
    "highPrecisionCoordinates": "True",
    "nonZeroCoordinates": "True"
  },
  "decimalLatitude": "29.641940",
  "scientificName": "Magnlolia Grandiflora",
  "countryCode": "USA"
}

**Comment by jotegui** [comment]
Hi Alex,

Thanks for your comment. Are you using the now obsolete "development" version, api-dev.vertnet-portal...? If so, please use the final API url api-geospatial.vertnet-portal...

Still, I am sorry, but I am unable to replicate your issue. When I check this URL:

http://api-geospatial.vertnet-portal.appspot.com/geospatial?decimalLatitude=29.641940&decimalLongitude=-82.336173&countryCode=USA&scientificName=Magnolia%20grandiflora

It returns

{

```
"decimalLongitude": "-82.336173",
"flags": 

{
    "hasCoordinates": true,
    "validCountry": true,
    "validCoordinates": true,
    "hasCountry": true,
    "coordinatesInsideCountry": true,
    "hasScientificName": true,
    "highPrecisionCoordinates": true,
    "nonZeroCoordinates": true
},
"decimalLatitude": "29.641940",
"scientificName": "Magnolia grandiflora",
"countryCode": "United States"
```

}

The API uses the iso3166 module, with ability to parse 2 and 3 letter country codes, and even full country names, so the API accepts "US", "USA", and "United States" as valid countryCode values (please, check out https://github.com/VertNet/api-geospatial/blob/master/geospatial/Parser.py#L173).

Can you send me the URL you used for your query?

Thanks!

**Comment by jotegui** [comment]
No further comments. Closing.
