### ISSUE TITLE
booleans returned as strings

### ISSUE THREAD

**Issue by sckott** [VertNet/api-geospatial#2]
The example request 

`curl 'http://api-dev.vertnet-portal.appspot.com/geospatial?decimalLongitude=42.82&decimalLatitude=-1.643&countryCode=ES' | jq .`

gives the booleans (true/false) as strings

``` json
 {
   "decimalLongitude": "42.82",
   "flags": {
     "negatedLatitude": "False",
     "hasScientificName": "False",
     "validCountry": "True",
     "negatedLongitude": "False",
     "validCoordinates": "True",
     "hasCountry": "True",
     "coordinatesInsideCountry": "False",
     "transposedCoordinates": "True",
     "hasCoordinates": "True",
     "highPrecisionCoordinates": "False",
     "nonZeroCoordinates": "True"
   },
   "decimalLatitude": "-1.643",
   "scientificName": "",
   "countryCode": "ES"
 }
```

shouldn't these be given back not as strings, like `http://api.gbif.org/v1/occurrence/search?limit=0`

``` json
{
  "offset": 0,
  "limit": 0,
  "endOfRecords": false,
  "count": 644041879,
  "results": [ ]
}
```

**Comment by jotegui** [comment]
Hi Scott,

Yes, unfortunately the supplemental material shows an outdated example
where booleans are returned as strings. However, the final version of the
API (api-geospatial.vertnet-portal...) returns properly formatted values.
Check this out:

http://api-geospatial.vertnet-portal.appspot.com/geospatial?decimalLongitude=42.82&decimalLatitude=1.643&countryCode=ES

## Hope this helps. Thanks and sorry for the confusion.

Javier Otegui
http://www.jotegui.com

**Comment by sckott** [comment]
ah, great, thanks, looks good
